WebAppYte/WebAppYte/Controllers/BSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAppYte.Models;

namespace WebAppYte.Controllers
{
    public class BSController : Controller
    {
        private readonly WebAppYteContext _context;

        public BSController(WebAppYteContext context)
        {
            _context = context;
        }

        // GET: BS
        public async Task<IActionResult> Index()
        {
            var webAppYteContext = _context.QuanTris.Include(q => q.IdkhoaNavigation);
            return View(await webAppYteContext.ToListAsync());
        }

        // GET: BS/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.QuanTris == null)
            {
                return NotFound();
            }

            var quanTri = await _context.QuanTris
                .Include(q => q.IdkhoaNavigation)
                .FirstOrDefaultAsync(m => m.IdquanTri == id);
            if (quanTri == null)
            {
                return NotFound();
            }

            return View(quanTri);
        }

        // GET: BS/Create
        public IActionResult Create()
        {
            ViewData["Idkhoa"] = new SelectList(_context.Khoas, "Idkhoa", "Idkhoa");
            return View();
        }

        // POST: BS/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdquanTri,TaiKhoan,MatKhau,VaiTro,ThongTinBacSi,TrinhDo,Idkhoa,HoTen,AnhBia,ThongtinZoom")] QuanTri quanTri)
        {
            if (ModelState.IsValid)
            {
                _context.Add(quanTri);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Idkhoa"] = new SelectList(_context.Khoas, "Idkhoa", "Idkhoa", quanTri.Idkhoa);
            return View(quanTri);
        }

        // GET: BS/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.QuanTris == null)
            {
                return NotFound();
            }

            var quanTri = await _context.QuanTris.FindAsync(id);
            if (quanTri == null)
            {
                return NotFound();
            }
            ViewData["Idkhoa"] = new SelectList(_context.Khoas, "Idkhoa", "Idkhoa", quanTri.Idkhoa);
            return View(quanTri);
        }

        // POST: BS/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdquanTri,TaiKhoan,MatKhau,VaiTro,ThongTinBacSi,TrinhDo,Idkhoa,HoTen,AnhBia,ThongtinZoom")] QuanTri quanTri)
        {
            if (id != quanTri.IdquanTri)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(quanTri);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuanTriExists(quanTri.IdquanTri))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Idkhoa"] = new SelectList(_context.Khoas, "Idkhoa", "Idkhoa", quanTri.Idkhoa);
            return View(quanTri);
        }

        // GET: BS/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.QuanTris == null)
            {
                return NotFound();
            }

            var quanTri = await _context.QuanTris
                .Include(q => q.IdkhoaNavigation)
                .FirstOrDefaultAsync(m => m.IdquanTri == id);
            if (quanTri == null)
            {
                return NotFound();
            }

            return View(quanTri);
        }

        // POST: BS/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.QuanTris == null)
            {
                return Problem("Entity set 'WebAppYteContext.QuanTris'  is null.");
            }
            var quanTri = await _context.QuanTris.FindAsync(id);
            if (quanTri != null)
            {
                _context.QuanTris.Remove(quanTri);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool QuanTriExists(int id)
        {
          return _context.QuanTris.Any(e => e.IdquanTri == id);
        }
    }
}

WebAppYte/WebAppYte/Controllers/LKController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAppYte.Models;

namespace WebAppYte.Controllers
{
    public class LKController : Controller
    {
        private readonly WebAppYteContext _context;

        public LKController(WebAppYteContext context)
        {
            _context = context;
        }

        // GET: LK
        public async Task<IActionResult> Index()
        {
            var webAppYteContext = _context.LichKhams.Include(l => l.IdnguoiDungNavigation).Include(l => l.IdquanTriNavigation);
            return View(await webAppYteContext.ToListAsync());
        }

        // GET: LK/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.LichKhams == null)
            {
                return NotFound();
            }

            var lichKham = await _context.LichKhams
                .Include(l => l.IdnguoiDungNavigation)
                .Include(l => l.IdquanTriNavigation)
                .FirstOrDefaultAsync(m => m.IdlichKham == id);
            if (lichKham == null)
            {
                return NotFound();
            }

            return View(lichKham);
        }

        // GET: LK/Create
        public IActionResult Create()
        {
            ViewData["IdnguoiDung"] = new SelectList(_context.NguoiDungs, "IdnguoiDung", "IdnguoiDung");
            ViewData["IdquanTri"] = new SelectList(_context.QuanTris, "IdquanTri", "IdquanTri");
            return View();
        }

        // POST: LK/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdlichKham,ChuDe,MoTa,BatDau,KetThuc,TrangThai,ZoomInfo,KetQuaKham,IdnguoiDung,IdquanTri")] LichKham lichKham)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lichKham);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdnguoiDung"] = new SelectList(_context.NguoiDungs, "IdnguoiDung", "IdnguoiDung", lichKham.IdnguoiDung);
            ViewData["IdquanTri"] = new SelectList(_context.QuanTris, "IdquanTri", "IdquanTri", lichKham.IdquanTri);
            return View(lichKham);
        }

        // GET: LK/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.LichKhams == null)
            {
                return NotFound();
            }

            var lichKham = await _context.LichKhams.FindAsync(id);
            if (lichKham == null)
            {
                return NotFound();
            }
            ViewData["IdnguoiDung"] = new SelectList(_context.NguoiDungs, "IdnguoiDung", "IdnguoiDung", lichKham.IdnguoiDung);
            ViewData["IdquanTri"] = new SelectList(_context.QuanTris, "IdquanTri", "IdquanTri", lichKham.IdquanTri);
            return View(lichKham);
        }

        // POST: LK/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdlichKham,ChuDe,MoTa,BatDau,KetThuc,TrangThai,ZoomInfo,KetQuaKham,IdnguoiDung,IdquanTri")] LichKham lichKham)
        {
            if (id != lichKham.IdlichKham)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lichKham);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LichKhamExists(lichKham.IdlichKham))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdnguoiDung"] = new SelectList(_context.NguoiDungs, "IdnguoiDung", "IdnguoiDung", lichKham.IdnguoiDung);
            ViewData["IdquanTri"] = new SelectList(_context.QuanTris, "IdquanTri", "IdquanTri", lichKham.IdquanTri);
            return View(lichKham);
        }

        // GET: LK/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.LichKhams == null)
            {
                return NotFound();
            }

            var lichKham = await _context.LichKhams
                .Include(l => l.IdnguoiDungNavigation)
                .Include(l => l.IdquanTriNavigation)
                .FirstOrDefaultAsync(m => m.IdlichKham == id);
            if (lichKham == null)
            {
                return NotFound();
            }

            return View(lichKham);
        }

        // POST: LK/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.LichKhams == null)
            {
                return Problem("Entity set 'WebAppYteContext.LichKhams'  is null.");
            }
            var lichKham = await _context.LichKhams.FindAsync(id);
            if (lichKham != null)
            {
                _context.LichKhams.Remove(lichKham);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LichKhamExists(int id)
        {
          return _context.LichKhams.Any(e => e.IdlichKham == id);
        }
    }
}

WebAppYte/WebAppYte/Views/Shared/_Layout - Copy.cshtml
@using Newtonsoft.Json;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppYte</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppYte.styles.css" asp-append-version="true" />
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        .navbar {
            position: fixed;
            height: 100vh;
            left: 0;
            top: 0;
            margin-right: -1px;
        }

        .navbar-nav {
            width: 100%;
            text-align: center;
            margin-top: 25%;
        }

            .navbar-nav > li {
                display: block;
                margin-bottom: 10px;
            }

        .container {
            padding-left: 220px; /* Adjust this value according to your navbar width */
        }
    </style>
</head>
<body>

   @* @using WebAppYte.Models

    @{
        NguoiDung u = null;
        try
        {
            var jsonString = Context.Session.GetString("user");
            if (!string.IsNullOrEmpty(jsonString))
            {
                u = JsonConvert.DeserializeObject<NguoiDung>(jsonString);
            }
        }
        catch (Exception ex)
        {
            // Log or handle the exception accordingly
            Console.WriteLine($"Error during deserialization: {ex.Message}");
        }
        QuanTri userBS = null;
        try
        {
            var jsonStringBS = Context.Session.GetString("userBS");
            if (!string.IsNullOrEmpty(jsonStringBS))
            {
                userBS = JsonConvert.DeserializeObject<QuanTri>(jsonStringBS);
            }
        }
        catch (Exception ex)
        {
            // Log or handle the exception accordingly
            Console.WriteLine($"Error during deserialization of userBS: {ex.Message}");
        }

        QuanTri userAdmin = null;
        try
        {
            var jsonStringBSs = Context.Session.GetString("userAdmin");
            if (!string.IsNullOrEmpty(jsonStringBSs))
            {
                userAdmin = JsonConvert.DeserializeObject<QuanTri>(jsonStringBSs);
            }
        }
        catch (Exception ex)
        {
            // Log or handle the exception accordingly
            Console.WriteLine($"Error during deserialization of userBS: {ex.Message}");
        }
        //var userBS = Context.Session.GetString("userBS");
    }*@
    
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="nav navbar-nav">
               @* @{
                    if (userAdmin != null)
                    {
                        <ul class="nav navbar-nav">
                            <li>
                                <a class="nav-link text-dark" >TK @userAdmin.TaiKhoan</a>

                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="DangXuatBs">Đăng Xuất</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="nav navbar-nav">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Dangky">ĐĂNG KÝ  </a>

                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Dangnhap">ĐĂNG NHẬP</a>

                        </ul>

                    }
                }*@
            </div>
            <div class="nav navbar-nav">
                <a class="navbar-brand" href="#"><h1>ADMIN DB</h1></a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li>
                    <a asp-action="index" asp-controller="userad">Người Dùng</a>
                </li>
                <li>
                    <a asp-action="index" asp-controller="BS">Bác Sĩ</a>
                </li>
                <li>
                    <a asp-action="index" asp-controller="LK">Lịch Khám</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebAppYte/WebAppYte/Views/Shared/_Layout.cshtml
@using Newtonsoft.Json;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppYte</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppYte.styles.css" asp-append-version="true" />
</head>
<body>

    @using WebAppYte.Models

    @{
        NguoiDung u = null;
        try
        {
            var jsonString = Context.Session.GetString("user");
            if (!string.IsNullOrEmpty(jsonString))
            {
                u = JsonConvert.DeserializeObject<NguoiDung>(jsonString);
            }
        }
        catch (Exception ex)
        {
            // Log or handle the exception accordingly
            Console.WriteLine($"Error during deserialization: {ex.Message}");
        }
        QuanTri userBS = null;
        try
        {
            var jsonStringBS = Context.Session.GetString("userBS");
            if (!string.IsNullOrEmpty(jsonStringBS))
            {
                userBS = JsonConvert.DeserializeObject<QuanTri>(jsonStringBS);
            }
        }
        catch (Exception ex)
        {
            // Log or handle the exception accordingly
            Console.WriteLine($"Error during deserialization of userBS: {ex.Message}");
        }

        QuanTri userAdmin = null;
        try
        {
            var jsonStringBSs = Context.Session.GetString("userAdmin");
            if (!string.IsNullOrEmpty(jsonStringBSs))
            {
                userAdmin = JsonConvert.DeserializeObject<QuanTri>(jsonStringBSs);
            }
        }
        catch (Exception ex)
        {
            // Log or handle the exception accordingly
            Console.WriteLine($"Error during deserialization of userBS: {ex.Message}");
        }
        //var userBS = Context.Session.GetString("userBS");
    }


    @if (u == null && userBS == null)
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppYte</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bacsi" asp-action="Index">DANH SÁCH BÁC SĨ</a>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Dangky">ĐĂNG KÝ</a>

                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Dangnhap">ĐĂNG NHẬP</a>

                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container" style="text-align:center">
               Hotline:0123456789/
                Hòa Lạc - Thạch Thất - Hà Nội/
                Email: abc@gmail.com/
                &copy; 2024 - WebAppYte - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    }
    else
    {
        if (u != null && userBS == null)
        {
            <header>
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                    <div class="container-fluid">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppYte</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                </li>

                               
                                <li class="nav-item">
                                    <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                       MENU <b class="caret"></b>
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li>
                                            <a class="nav-link text-dark" asp-route-id="@u.IdnguoiDung" asp-area="" asp-controller="LichKham" asp-action="Index">LỊCH HẸN CỦA BẠN</a>

                                        <li><hr class="dropdown-divider" /></li>
                                        <li>
                                            <a class="nav-link text-dark" asp-area="" asp-controller="LichKham" asp-action="create" asp-route-id="@u.IdnguoiDung">ĐẶT LỊCH KHÁM</a>

                                    </ul>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Bacsi" asp-action="Index">DANH SÁCH BÁC SĨ</a>
                                </li>
                            </ul>
                            @{
                                if (u != null)
                                {
                                    <ul class="nav navbar-nav">
                                        <li>
                                            <a class="nav-link text-dark" asp-route-id="@u.IdnguoiDung" asp-area="" asp-controller="Nguoidung" asp-action="Details">Hồ sơ &nbsp; @u.TaiKhoan</a>

                                        </li>
                                        <li>
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="DangXuat">Đăng Xuất</a>
</li>
                                    </ul>
                                }
                                else
                                {
                                    <ul class="nav navbar-nav">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Dangky">ĐĂNG KÝ</a>

                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Dangnhap">ĐĂNG NHẬP</a>

                                    </ul>
                                   
                                }
                            }
                        </div>
                    </div>
                </nav>
            </header>
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

            <footer class="border-top footer text-muted">
                <div class="container" style="text-align:center">
                    Hotline:0123456789/
                    Hòa Lạc - Thạch Thất - Hà Nội/
                    Email: abc@gmail.com/
                    &copy; 2024 - WebAppYte - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </footer>
        }
        else
        {
            <header>
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                    <div class="container-fluid">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppYte</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                </li>
                             @*   <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Bacsi" asp-action="Quanlyhoidap">TRẢ LỜI CÂU HỎI</a>
                                </li>*@
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-route-id="@userBS.IdquanTri" asp-area="" asp-controller="Bacsi" asp-action="Kiemtralichhen">LỊCH TƯ VẤN KHÁM BỆNH</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Bacsi" asp-action="Index">DANH SÁCH BÁC SĨ</a>
                                </li>
                             
                            </ul>
                            @{
                                if (userBS != null)
                                {
                                    <ul class="nav navbar-nav">
                                        <li>
                                            <a class="nav-link text-dark" asp-route-id="@userBS.IdquanTri" asp-area="" asp-controller="Bacsi" asp-action="Details">Hồ sơ &nbsp; @userBS.TaiKhoan</a>

                                        </li>
                                        <li>
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="DangXuatBs">Đăng Xuất</a></li>
                                    </ul>
                                }
                                else
                                {
                                    <ul class="nav navbar-nav">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Dangky">ĐĂNG KÝ  </a>

                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Dangnhap">ĐĂNG NHẬP</a>

                                    </ul>
                                   
                                }
                            }
                        </div>
                    </div>
                </nav>
            </header>
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

            <footer class="border-top footer text-muted">
                <div class="container" style="text-align:center">
                    Hotline:0123456789/
                    Hòa Lạc - Thạch Thất - Hà Nội/
                    Email: abc@gmail.com/
                    &copy; 2024 - WebAppYte - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </footer>
        }
    }

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebAppYte/WebAppYte/Views/Shared/lay.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}