WebAppYte/WebAppYte/Controllers/BacsiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Net;
using WebAppYte.Models;
using X.PagedList;

namespace WebAppYte.Controllers
{
    public class BacsiController : Controller
    {
        private readonly WebAppYteContext db ;
        public BacsiController(WebAppYteContext context)
        {
            db = context;
        }
        // GET: Bacsi
        public ActionResult Index()
        {
            var quanTris = db.QuanTris.Include(q => q.IdkhoaNavigation).Where(x => x.VaiTro == 2);
            return View(quanTris.ToList());
        }

        //GET: Bacsi/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            QuanTri quanTri = db.QuanTris.Include(q => q.IdkhoaNavigation).FirstOrDefault(q => q.IdquanTri == id);

            if (quanTri == null)
            {
                return NotFound();
            }

            return View(quanTri);
        }

        // GET: Bacsi/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return  BadRequest();
            }
            QuanTri quanTri = db.QuanTris.Find(id);
            if (quanTri == null)
            {
                return NotFound();
            }
            ViewBag.Idkhoa = new SelectList(db.Khoas, "Idkhoa", "TenKhoa", quanTri.Idkhoa);
            return View(quanTri);
        }

        // POST: Bacsi/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind("IdquanTri,TaiKhoan,MatKhau,VaiTro,ThongTinBacSi,TrinhDo,Idkhoa,HoTen,AnhBia")] QuanTri quanTri)
        {
            if (ModelState.IsValid)
            {
                db.Entry(quanTri).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = quanTri.IdquanTri });
            }
            ViewBag.Idkhoa = new SelectList(db.Khoas, "Idkhoa", "TenKhoa", quanTri.Idkhoa);
            return View(quanTri);
        }

        // GET: Admin/QuanTris/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            QuanTri quanTri = db.QuanTris.Find(id);
            if (quanTri == null)
            {
                return NotFound();
            }
            return View(quanTri);
        }

        // POST: Admin/QuanTris/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            QuanTri quanTri = db.QuanTris.Find(id);
            db.QuanTris.Remove(quanTri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


      /*  public ActionResult Quanlyhoidap(int? page)
        {
            if (page == null) page = 1;
            var hoiDaps = db.HoiDaps.Include(h => h.IdnguoiDungNavigation).Include(h => h.IdquanTriNavigation).Where(n => n.TrangThai == 0).OrderByDescending(a => a.NgayGui).ThenBy(a => a.Idhoidap).ToList();
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(hoiDaps.ToPagedList(pageNumber, pageSize));
        }
*/
        public ActionResult Traloicauhoi(int? id)
        {
            if (id == null)

            {
                return  BadRequest();
            }
            HoiDap hoiDap = db.HoiDaps.Find(id);
            if (hoiDap == null)
            {
                return NotFound();
            }
            ViewBag.IDNguoiDung = new SelectList(db.NguoiDungs, "IDNguoiDung", "HoTen", hoiDap.IdnguoiDung);
            ViewBag.IDQuanTri = new SelectList(db.QuanTris, "IDQuanTri", "TaiKhoan", hoiDap.IdquanTri);
            return View(hoiDap);
        }

        // POST: Hoidap/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Traloicauhoi([Bind("IDHoidap,CauHoi,TraLoi,IDNguoiDung,IDQuanTri,NgayGui,GhiChu,TrangThai")] HoiDap hoiDap)
        {
            if (ModelState.IsValid)
            {
                hoiDap.TrangThai = 1;
                db.Entry(hoiDap).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Quanlyhoidap");
            }
            ViewBag.IDNguoiDung = new SelectList(db.NguoiDungs, "IDNguoiDung", "HoTen", hoiDap.IdnguoiDung);
            ViewBag.IDQuanTri = new SelectList(db.QuanTris, "IDQuanTri", "TaiKhoan", hoiDap.IdquanTri);
            return View(hoiDap);
        }

        public ActionResult Kiemtralichhen(int? page, int id)
        {
            // Check if db.LichKhams is not null
            if (db.LichKhams != null)
            {
                var lich = db.LichKhams
                    .Include(l => l.IdnguoiDungNavigation)
                    .Where(l => l.IdquanTri == id)  // Include the navigation property
                    .OrderByDescending(x => x.BatDau)
                    .ThenBy(y => y.IdlichKham)
                    .ToList();

                int pageSize = 5;
                int pageNumber = (page ?? 1);

                return View(lich.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                // Handle the case where db.LichKhams is null
                // You can return an appropriate view or redirect to an error page
                return View("Error");
            }
        }

        public ActionResult Lichdangcho(int? page)
        {
            var lich = db.LichKhams.OrderByDescending(x => x.BatDau).ThenBy(y => y.IdlichKham).Where(x => x.TrangThai == 0).ToList();
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(lich);

            //return View(lich.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult Lichdaxacnhan(int? page)
        {
            var lich = db.LichKhams.OrderByDescending(x => x.BatDau).ThenBy(y => y.IdlichKham).Where(x => x.TrangThai == 1).ToList();
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(lich);

            // return View(lich.ToPagedList(pageNumber, pageSize));
        }

        // GET: LichKham/Edit/5
        public async Task<IActionResult> Xacnhanlichhen(int? id)
        {
            if (id == null || db.LichKhams == null)
            {
                return NotFound();
            }

            var lichKham = await db.LichKhams.FindAsync(id);
            if (lichKham == null)
            {
                return NotFound();
            }
            ViewData["IdnguoiDung"] = new SelectList(db.NguoiDungs, "IdnguoiDung", "HoTen", lichKham.IdnguoiDung);
            ViewData["IdquanTri"] = new SelectList(db.QuanTris, "IdquanTri", "HoTen", lichKham.IdquanTri);
            return View(lichKham);
        }

        // POST: LichKham/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Xacnhanlichhen(int id, [Bind("IdlichKham,ChuDe,MoTa,BatDau,KetThuc,TrangThai,ZoomInfo,KetQuaKham,IdnguoiDung,IdquanTri")] LichKham lichKham)
        {
            if (id != lichKham.IdlichKham)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(lichKham);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LichKhamExists(lichKham.IdlichKham))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Kiemtralichhen), new { id = lichKham.IdquanTri });
            }
            ViewData["IdnguoiDung"] = new SelectList(db.NguoiDungs, "IdnguoiDung", "HoTen", lichKham.IdnguoiDung);
            ViewData["IdquanTri"] = new SelectList(db.QuanTris, "IdquanTri", "HoTen", lichKham.IdquanTri);
            return View(lichKham);
        }

        private bool LichKhamExists(int id)
        {
            return db.LichKhams.Any(e => e.IdlichKham == id);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebAppYte/WebAppYte/Views/Bacsi/Details.cshtml
@model WebAppYte.Models.QuanTri

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>QuanTri</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdkhoaNavigation.TenKhoa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdkhoaNavigation.TenKhoa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaiKhoan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaiKhoan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VaiTro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VaiTro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThongTinBacSi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThongTinBacSi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrinhDo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrinhDo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhBia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhBia)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdquanTri }) |
    @*@Html.ActionLink("Back to List", "Index")*@
</p>

WebAppYte/WebAppYte/Views/Bacsi/Edit.cshtml
@model WebAppYte.Models.QuanTri

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>QuanTri</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdquanTri)

        <div class="form-group">
            @Html.LabelFor(model => model.TaiKhoan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaiKhoan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VaiTro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VaiTro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VaiTro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThongTinBacSi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThongTinBacSi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThongTinBacSi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrinhDo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrinhDo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrinhDo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdkhoaNavigation, "Idkhoa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Idkhoa", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdkhoaNavigation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhBia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhBia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnhBia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebAppYte/WebAppYte/Views/Bacsi/Index.cshtml
@model IEnumerable<WebAppYte.Models.QuanTri>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using Newtonsoft.Json;
@using WebAppYte.Models

@{
    NguoiDung u = null;
    try
    {
        var jsonString = Context.Session.GetString("user");
        if (!string.IsNullOrEmpty(jsonString))
        {
            u = JsonConvert.DeserializeObject<NguoiDung>(jsonString);
        }
    }
    catch (Exception ex)
    {
        // Log or handle the exception accordingly
        Console.WriteLine($"Error during deserialization: {ex.Message}");
    }
    QuanTri userBS = null;
    try
    {
        var jsonStringBS = Context.Session.GetString("userBS");
        if (!string.IsNullOrEmpty(jsonStringBS))
        {
            userBS = JsonConvert.DeserializeObject<QuanTri>(jsonStringBS);
        }
    }
    catch (Exception ex)
    {
        // Log or handle the exception accordingly
        Console.WriteLine($"Error during deserialization of userBS: {ex.Message}");
    }
    //var userBS = Context.Session.GetString("userBS");
}
<style>
    img {
    margin-right: 20px;
    }
</style>
<center><h2>DANH SÁCH BÁC SỸ HỖ TRỢ</h2></center>
<hr />
@*<center><img src="~/Common/images/bs.jpg" width="800px" height="250px" /></center>*@

<div class="row">
    <br />
    @if (u == null && userBS == null)
    {
        @foreach (var item in Model)
        {
            <div class="col-md-6">

                <img class="imgavt" src="https://www.murrayglass.com/wp-content/uploads/2020/10/avatar-scaled.jpeg" width="160" height="160" style="float:left" />
                <br />
                <h5>Họ và tên: @item.HoTen</h5>
                <h5>Trình độ: @item.TrinhDo</h5>
                <h5>Khoa: @item.IdkhoaNavigation.TenKhoa</h5>
                <h5>Thông tin khác : @item.ThongTinBacSi</h5>
                <hr />
            </div>
        }

    }
    else if (userBS != null)
    {


        @foreach (var item in Model)
        {
            <div class="col-md-6">

                <img class="imgavt" src="https://www.murrayglass.com/wp-content/uploads/2020/10/avatar-scaled.jpeg" width="160" height="160" style="float:left" />
                <br />
                <h5>Họ và tên: @item.HoTen</h5>
                <h5>Trình độ: @item.TrinhDo</h5>
                <h5>Khoa: @item.IdkhoaNavigation.TenKhoa</h5>
                <h5>Thông tin khác : @item.ThongTinBacSi</h5>
                <hr />
            </div>
        }
    }
    else
    {
        @foreach (var item in Model)
        {
            <div class="col-md-6">

                <img class="imgavt" src="https://www.murrayglass.com/wp-content/uploads/2020/10/avatar-scaled.jpeg" width="160" height="160" style="float:left" />
                <br />
                <h5>Họ và tên: @item.HoTen</h5>
                <h5>Trình độ: @item.TrinhDo</h5>
                <h5>Khoa: @item.IdkhoaNavigation.TenKhoa</h5>
                <h5>Thông tin khác : @item.ThongTinBacSi</h5>
                <hr />
            </div>
        }
        <center>
            <h3> 
                @*<a href="@Url.Action("Index", "LichKham")">ĐẶT LỊCH KHÁM</a>*@
                <a asp-action="Create" asp-controller="LichKham" asp-route-id="@u.IdnguoiDung">ĐẶT LỊCH KHÁM</a> |

            </h3>
            <br />
        </center>
    }
   
</div>

WebAppYte/WebAppYte/Views/Bacsi/Kiemtralichhen.cshtml
@using Newtonsoft.Json;
@*@model PagedList.IPagedList<WebAppYte.Models.LichKham>
@using PagedList.Mvc;*@
@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<WebAppYte.Models.LichKham>

@{
    ViewBag.Title = "Kiemtralichhen";
    Layout = "~/Views/Shared/_Layout.cshtml";
    QuanTri userBS = null;
    try
    {
        var jsonStringBS = Context.Session.GetString("userBS");
        if (!string.IsNullOrEmpty(jsonStringBS))
        {
            userBS = JsonConvert.DeserializeObject<QuanTri>(jsonStringBS);
        }
    }
    catch (Exception ex)
    {
        // Log or handle the exception accordingly
        Console.WriteLine($"Error during deserialization of userBS: {ex.Message}");
    }
}

<hr />
<h2>DANH SÁCH LỊCH HẸN</h2>
<hr />
@*<h4>
    <a href="@Url.Action("Lichdangcho", "Bacsi", new { id = userBS.IdquanTri  })">LỊCH CHƯA XÁC NHẬN</a>&nbsp;||
    <a href="@Url.Action("Lichdaxacnhan", "Bacsi", new { id = userBS.IdquanTri  })">LỊCH ĐÃ XÁC NHẬN</a>&nbsp;||
    <a href="@Url.Action("Kiemtralichhen", "Bacsi", new { id = userBS.IdquanTri  })">TẤT CẢ LỊCH HẸN</a>
</h4>*@
<!-- Ô tìm kiếm -->
<div>
    <label for="searchStatus">Tìm theo trạng thái:</label>
    <select id="searchStatus">
        <option value="">Tất cả</option>
        <option value="Đang chờ xác nhận">Đang chờ xác nhận</option>
        <option value="Đã xác nhận lịch">Đã xác nhận lịch</option>
        <option value="Đã tư vấn xong">Đã tư vấn xong</option>
        <option value="Từ chối lịch hẹn">Từ chối lịch hẹn</option>
        <option value="Hủy">Hủy</option>
    </select>
    <button onclick="search()">Tìm</button>
</div>


<br />
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                Người đặt lịch
            </th>
            @*<th>
            Bác sĩ tư vấn
            </th>*@
            <th>
                Nội dung cần tư vấn
            </th>
            @*<th>
            Mô tả
            </th>*@
            <th>
                Hẹn vào lúc
            </th>
            @*<th>
            Kết thúc lúc
            </th>*@
            <th>
                Trạng thái
            </th>
            <th>
                ZOOM
            </th>
            <th>
                Ghi chú tư vấn
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdnguoiDungNavigation.HoTen)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ChuDe)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BatDau)
                </td>
                <td>
                    @{
                        if (item.TrangThai == 0)
                        {
                            <h5 style="color:red">Đang chờ xác nhận </h5>
                        }
                        else if (item.TrangThai == 1)
                        {
                            <h5 style="color:orangered">Đã xác nhận lịch </h5>
                        }
                        else if (item.TrangThai == 2)
                        {
                            <h5 style="color:gold">Đã tư vấn xong </h5>
                        }
                        else if (item.TrangThai == 3)
                        {
                            <h5 style="color:darkgoldenrod">Từ chối lịch hẹn </h5>
                        }
                        else if (item.TrangThai == 4)
                        {
                            <h5 style="color:darkgoldenrod">Hủy </h5>
                        }
                        else
                        {
                            <h5 style="color:red">Lỗi </h5>
                        }
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ZoomInfo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KetQuaKham)
                </td>
                <td>
                    @{
                        if (item.TrangThai == 0)
                        {
                            <a asp-action="Xacnhanlichhen" asp-route-id="@item.IdlichKham">Xác nhận</a>
                        }
                        else if (item.TrangThai == 1)
                        {
                        }
                        else if (item.TrangThai == 2)
                        {
                        }
                        else if (item.TrangThai == 3)
                        {
                        }
                        else if (item.TrangThai == 4)
                        {
                        }
                        else
                        {
                        }
                    }
                </td>
            </tr>
        }
    </tbody>


</table>
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Kiemtralichhen",
        new { page }))


@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page }))
<!-- Kết thúc -->
<script>
    function search() {
        var status = document.getElementById("searchStatus").value;
        var rows = document.querySelectorAll(".table tbody tr");

        rows.forEach(function (row) {
            row.style.display = "none";
            var rowStatus = row.querySelector("td:nth-child(4)").innerText.trim();
            if (status === "" || rowStatus === status) {
                row.style.display = "";
            }
        });
    }
</script>

WebAppYte/WebAppYte/Views/Bacsi/Lichdangcho.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

WebAppYte/WebAppYte/Views/Bacsi/Lichdaxacnhan.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

WebAppYte/WebAppYte/Views/Bacsi/Quanlyhoidap.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

WebAppYte/WebAppYte/Views/Bacsi/Traloicauhoi.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}